version: 2.1

jobs:
  build:
    docker:
      - image: jfrimmel/cirq:1.0
    steps:
      - checkout
      - run:
          name: Build the site
          command: ninja
      - run:
          name: Output static files
          command: find build/site -print0 | sort -z | xargs -0 -n 1 echo

workflows:
  ci:
    jobs:
      - build