version: 2.1

jobs:
  build:
    docker:
      - image: jfrimmel/cirq:2.2
    steps:
      - checkout
      - run:
          name: Build the site
          command: ninja
      - run:
          name: Output static files
          command: find build/site -print0 | sort -z | xargs -0 -n 1 echo
      - persist_to_workspace:
          root: build
          paths: site
  deploy:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Disable jekyll builds
          command: touch build/site/.nojekyll
      - run:
          name: Adopt PWA to GitHub Pages entry point
          command: |
            # Change the entry-point from `/` to `/cirq`
            sed -i 's|"/"|"/cirq"|' build/site/manifest.json
            # prepend `/cirq` to the `SITE_RESOURCES`-array
            sed -i '/SITE_RESOURCES/,/\]/ s@\(^ *"/\)@\1cirq/@' build/site/worker.js
      - run:
          # https://discuss.circleci.com/t/cant-ignore-the-gh-pages-branch/2002/4
          name: Add CircleCI definitions for this branch
          command: mkdir build/site/.circleci && cp .circleci/config.yml build/site/.circleci/config.yml
      - run:
          name: Install and configure gh-pages
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config --global user.email ci-build@cirq
            git config --global user.name ci-build
      - add_ssh_keys:
          fingerprints:
            - "c9:5a:b6:dc:8c:36:9f:7c:67:bb:0a:3a:c6:6d:87:9b"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message '[skip ci] Updates' --dist build/site


workflows:
  ci:
    jobs:
      - build
      - deploy:
          requires: [build]
          filters:
            branches:
              only: main
